name: Deploy AI Logistics Platform to GKE

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/280714936496/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-deployer@ai-logistics-platform.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t asia-south1-docker.pkg.dev/ai-logistics-platform/ai-repo/ai-backend:latest .

      - name: Push Docker image
        run: |
          docker push asia-south1-docker.pkg.dev/ai-logistics-platform/ai-repo/ai-backend:latest

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials logistics-cluster --zone asia-south1-a

      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml